### ISSUE TITLE
Alert manager config error after kepth configure the conitoring

### ISSUE THREAD

**Issue by zoftdev** [keptn-contrib/prometheus-service#318]
Keptn: 0.15.0
Prometheus-service:0.8.0
Prometheus Helm:latest
Alert Manager :  0.23.0 & 0.24.0

Command:
>keptn configure monitoring prometheus --project=sockshop --service=carts

After restart Alert Manager Pod,  it  will crash loop back off with logs:

> ts=2022-06-16T06:00:20.650Z caller=coordinator.go:118 level=error component=configuration msg="Loading configuration file failed" file=/etc/config/alertmanager.yml err="yaml: unmarshal errors:\n  line 5: field enable_http2 not found in type config.plain\n  line 33: field enable_http2 not found in type config.plain"

**Comment by Raffy23** [comment]
Hi, I'm currently not sure how this error is caused by the prometheus-service, because we only write a [static](https://github.com/keptn-contrib/prometheus-service/blob/master/utils/prometheus/prometheus.go#L62-L81) configuration yaml for the altermanager, which does not include the mentioned field. 
Could it be that there is another service running that could overwrite the config map?

**Comment by christian-kreuzberger-dtx** [comment]
Hi @zoftdev, any update on this?

**Comment by christian-kreuzberger-dtx** [comment]
We have identified the root-cause, which is an incompatibility of prometheus/common library and alertmanager.
@Raffy23 is working on a fix.

**Comment by Raffy23** [comment]
Hi @zoftdev, do you still have problems with the alertmanager? If so have you already tried out the the version [0.8.3](https://github.com/keptn-contrib/prometheus-service/releases/tag/0.8.3)?
