### ISSUE TITLE
Handle queries for which no data points are available

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn-contrib/prometheus-service#41]
From https://github.com/keptn/keptn/issues/1496

Currently, if we receive a result from Prometheus containing an empty array, such as the following:

```
{
    "status": "success",
    "data": {
        "resultType": "vector",
        "result": []
    }
}
```

we assume that the value for the queried metric is 0.

**Example 1:** If the error rate gets queried and the error rate of the service was 0, the Prometheus API will send the object listed above and prometheus-service will interpret it as a `0`.

**Example 2:** If the response time gets queried, but Prometheus sends the empty result from above, prometheus-service interprets it as a `0`.

Based on the query, the result has different semantics; i.e. it could mean that no data is available and we cannot retrieve a value.

A solution is proposed in https://github.com/keptn-contrib/prometheus-service/issues/41#issuecomment-1109382656

**Comment by jurgen-weber-deltatre** [comment]
Hi

Yes, I have experienced this using SLI/SLO during the evaluation stage. The SLO

```
---
spec_version: "1.0"
comparison:
  aggregate_function: "avg"
  compare_with: "single_result"
  include_result_with_score: "pass"
  number_of_comparison_results: 1
filter:
objectives:
  - sli: "response_time_p95"
    displayName: "Response time P95"
    key_sli: false
    pass:             # pass if (relative change <= 10% AND absolute value is < 600ms)
      - criteria:
          - "<=+10%"  # relative values require a prefixed sign (plus or minus)
          - "<600"    # absolute values only require a logical operator
    warning:          # if the response time is below 800ms, the result should be a warning
      - criteria:
          - "<=800"
    weight: 1
total_score:
  pass: "90%"
  ```
  
  and then the SLI
  ```
   ---
 spec_version: '1.0'
 indicators:
-  response_time_p50: histogram_quantile(0.5, sum by(le) (rate(http_response_time_milliseconds_bucket{handler="ItemsController.addToCart",job="$SERVICE-$PROJECT-$STAGE-canary"}[$DURATION_SECONDS])))
-  response_time_p90: histogram_quantile(0.9, sum by(le) (rate(http_response_time_milliseconds_bucket{handler="ItemsController.addToCart",job="$SERVICE-$PROJECT-$STAGE-canary"}[$DURATION_SECONDS])))
-  response_time_p95: histogram_quantile(0.95, sum by(le) (rate(http_response_time_milliseconds_bucket{handler="ItemsController.addToCart",job="$SERVICE-$PROJECT-$STAGE-canary"}[$DURATION_SECONDS])))
```

my metric 'http_response_time_milliseconds_bucket' did not have the label value 'ItemsController.addToCart' for the label 'handler'... This means when Prometheus returns nothing (as in no data, a query without result) but I could quite clearly see that the evaluation phase is returning 0.

![image](https://user-images.githubusercontent.com/77422409/165230796-6776c4b6-34a4-4589-94a4-bcef57e85b03.png)

So this then DEPLOYED a broken metric/SLI because it considered it 0 whcih gave it a pass score. IMO if a metric returns no data it should fail.

This then proved problematic for the relative baseline criteria of "<=+10%" because my change was quite large from 0 to an actual value, as shown:

![image](https://user-images.githubusercontent.com/77422409/165230772-7cd3040c-5b69-45b8-8dc6-57d2bdf70e3e.png)

**Comment by johannes-b** [comment]
A similar discussion already happened in the context of the `dynatrace-service` (which is another SLI provider). There we agreed on the following behavior - see discussion here for more details: https://github.com/keptn-contrib/dynatrace-service/discussions/704 

| Description | `status` | `result` | Consequence |
| --- | --- | --- | --- |
| **The new case**<br>If the processing of the result cannot produce a single value<br>- due to no data points being returned, <br>- multiple data points being returned, <br>- or not being able to select a single result value. |  `succeeded` | `warning` | - the `success` field of the individual indicator in `indicatorValues` is set to `false`<br> - an SLI retrieval was performed<br><br> -> lighthouse-service has to deal with SLIs that have no value |


To deal with the issue of no data points for a certain SLI, I propose to align the behavior of the prometheus-service to the behavior of the dynatrace-service (see above).

**Comment by johannes-b** [comment]
@christian-kreuzberger-dtx do you agree that this is corrective maintenance (`label:bug`) since the quality gate opens even though no data is provided?

**Comment by christian-kreuzberger-dtx** [comment]
I agree, this is a bug.
As a workaround for @jurgen-weber-deltatre , I recommend "invalidating" previous evaluations in Bridge.

**Comment by jurgen-weber-deltatre** [comment]
is that the 'ignore for comparison' button? Ok, Thanks.
